[sip_test_1001]
type=friend
host=dynamic
context=agents
secret=Test1234
dtmfmode=rfc2833
canreinvite=no
disallow=all
allow=ulaw
allow=alaw
nat=force_rport,comedia
qualify=yes
[sip_pub_b4e855_1002]
type=friend
host=dynamic
context=agents
secret=oqe9spl694
dtmfmode=rfc2833
canreinvite=no
disallow=all
allow=ulaw
allow=alaw
nat=force_rport,comedia
qualify=yes
