[globals]
BACKEND_URL=http://backend:3000
MOH=default
MAX_QUEUE_WAIT=120
GSM_TIMEOUT=20

[from-gsm]
exten => _X.,1,NoOp(GSM CALL: ${CALLERID(num)})
 same => n,Goto(agents,1002,1)

[from-voip]
exten => _X.,1,NoOp(VOIP CALL: ${CALLERID(num)})
 same => n,Goto(agents,1002,1)

[agents]
exten => 1001,1,Dial(SIP/sip_test_1001,30,tT)
 same => n,Hangup()
exten => 1002,1,Dial(SIP/sip_pub_b4e855_1002,30,tT)
 same => n,Hangup()

[default]
exten => s,1,Hangup()
exten => i,1,Hangup()
exten => t,1,Hangup()
